-- 第三方链接squid  add yi.zhou 2014/11/10
 drop table if  exists DS_WEBSERVICE_CONNECTION;
create table DS_WEBSERVICE_CONNECTION
(
	id 					int not null,
    is_restful			char(1),
	address				varchar(200),
	primary key(id)
);
drop table if  exists DS_HTTP_CONNECTION;
create table DS_HTTP_CONNECTION
(
   id 					int not null,
   host 				varchar(30) null,
   port 				int null,
   primary key(id)
);


drop table if  exists DS_THIRDPARTY_PARAMS;
create table DS_THIRDPARTY_PARAMS
(
	id                  int not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
	squid_id            int,
	source_table_id     int,
	name                varchar(200),
	params_type         int,
	value_type          int,
	val                 varchar(200),
	column_id           int,
	variable_id         int,
	ref_squid_id        int,
	primary key(id)
);
--alter table DS_THIRDPARTY_PARAMS add constraint Fk_Thrid_party_source_table_id foreign key (SOURCE_TABLE_ID)
--	  references DS_SOURCE_TABLE(id);
alter table DS_THIRDPARTY_PARAMS add constraint FK_thrid_party_id foreign key (squid_id)
      references DS_SQUID (id);

alter table DS_SOURCE_TABLE add column method int;
drop table if  exists DS_GIS_MAP_SQUID;
create table  DS_GIS_MAP_SQUID
(
  id                   int not null,
   map_name          varchar(50) ,
   map_template      clob ,
  is_support_history   boolean ,
   max_history_count    int,
   is_send_email        boolean ,
   email_receivers      varchar(500) ,
   email_title          varchar(200) ,
   email_report_format  varchar(10) ,
   creation_date        datetime ,
   is_real_time         boolean,
   folder_id            int,
   is_packed            boolean,
   is_compressed        boolean,
   is_encrypted         boolean,
   password             varchar(10),
   primary key (id)
);

alter table DS_GIS_MAP_SQUID add constraint FK_squid_id_temp foreign key (id)
      references DS_SQUID (id);

-- added by yi.zhou  添加变量 (variable)
drop table if  exists DS_VARIABLE;
create table DS_VARIABLE
(
	id                  int not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
	project_id			int,
	squid_flow_id		int,
	squid_id 			int,
	variable_scope 		int, --0:project、1:squidflow、2:squidModelBase
	variable_name       varchar(200),
	variable_type		int,
	variable_length		int,
	variable_precision	int,
	variable_scale		int,
	variable_value		varchar(500),
	add_date 			timestamp not null,
	primary key (id)
);
 
  --added by yi.zhou 2014-12-26  FormatDate Transformation的属性 对应枚举 DateFormatEnum
 alter table DS_transformation add column date_format int;
 
 --update by yi.zhou 2015-1-4 支持引用transformation  更新
alter table ds_transformation alter column term_index varchar(100);
alter table ds_transformation alter column replica_count varchar(100);
alter table ds_transformation alter column Length varchar(100);
alter table ds_transformation alter column start_position varchar(100);
alter table ds_transformation alter column power varchar(100);
alter table ds_transformation alter column Modulus varchar(100);

-- added by yi.zhou DESTWS(SquidModelBase)
drop table if exists DS_DEST_WEBSERVICE;
create table DS_DEST_WEBSERVICE
(
	id                   int not null,
	service_name 		 varchar(100),
	wsdl                 varchar(200),
	is_realtime 		 char(1),
	callback_url		 varchar(200),
	allowed_services     varchar(200),
	primary key(id)
);

alter table DS_THIRDPARTY_PARAMS drop column variable_id;

create table DS_START_SQUID_FLOW_LOG
(
	id                  int not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
	task_id				varchar(200),
	call_back_url		int,
	create_date			datetime,
	call_back_date		datetime,
	primary key(id)
);
-- added by yi.zhou  添加报表历史版本 (report_version)
drop table if  exists DS_REPORT_VERSION;
create table DS_REPORT_VERSION
(
	id                int not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
	squid_id 		  int not null,
	version 		  int,
	template      	  clob ,
	add_date 		  timestamp not null,
	primary key (id)
);

--added by yi.zhou  transformation
--alter table DS_TRANSFORMATION add column inc_unit int;

--added by yi.zhou column
alter table DS_COLUMN add column sort_level int; 
alter table DS_COLUMN add column sort_type int;

--added by yi.zhou column
alter table DS_TRANSFORMATION alter column delimiter varchar(2000);
alter table DS_TRANSFORMATION add column split_type int;


--added by akachi 2015-04-24
insert into DS_SYS_USER (KEY,USER_NAME,PASSWORD,FULL_NAME,EMAIL_ADDRESS,IS_ACTIVE) values ('58610ba8-5225-4300-81a2-b73dd5bdc168','superuser','7066a4f427769cc43347aa96b72931a','superuser','www.eurlanda.com','N')

--added by yi.zhou 2015-06-12
alter table ds_transformation alter column date_format varchar(100);

update ds_transformation set date_format='MM/dd/yy' where transformation_type_id='35' and date_format='0';
update ds_transformation set date_format='MM/dd/yyyy' where transformation_type_id='35' and date_format='1';
update ds_transformation set date_format='yy.MM.dd' where transformation_type_id='35' and date_format='2';
update ds_transformation set date_format='yyyy.MM.dd' where transformation_type_id='35' and date_format='3';
update ds_transformation set date_format='dd/MM/yy' where transformation_type_id='35' and date_format='4';
update ds_transformation set date_format='dd/MM/yyyy' where transformation_type_id='35' and date_format='5';
update ds_transformation set date_format='dd.MM.yy' where transformation_type_id='35' and date_format='6';
update ds_transformation set date_format='dd.MM.yyyy' where transformation_type_id='35' and date_format='7';
update ds_transformation set date_format='dd-MM-yy' where transformation_type_id='35' and date_format='8';
update ds_transformation set date_format='dd-MM-yyyy' where transformation_type_id='35' and date_format='9';
update ds_transformation set date_format='dd MM yyyy' where transformation_type_id='35' and date_format='10';
update ds_transformation set date_format='dd MM yyyy' where transformation_type_id='35' and date_format='11';
update ds_transformation set date_format='MMM dd), yy' where transformation_type_id='35' and date_format='12';
update ds_transformation set date_format='MMM dd), yyyy' where transformation_type_id='35' and date_format='13';
update ds_transformation set date_format='HH:mm:ss' where transformation_type_id='35' and date_format='14';
update ds_transformation set date_format='MMM dd yyyy HH:mm:ss' where transformation_type_id='35' and date_format='15';
update ds_transformation set date_format='MM-dd-yy' where transformation_type_id='35' and date_format='16';
update ds_transformation set date_format='MM-dd-yyyy' where transformation_type_id='35' and date_format='17';
update ds_transformation set date_format='yy-MM-dd' where transformation_type_id='35' and date_format='18';
update ds_transformation set date_format='yyyy-MM-dd' where transformation_type_id='35' and date_format='19';
update ds_transformation set date_format='yyMMdd' where transformation_type_id='35' and date_format='20';
update ds_transformation set date_format='yyyyMMdd' where transformation_type_id='35' and date_format='21';
update ds_transformation set date_format='dd MMM yyyy HH:mm:ss:SSS' where transformation_type_id='35' and date_format='22';
update ds_transformation set date_format='HH:mm:ss:SSS' where transformation_type_id='35' and date_format='23';
update ds_transformation set date_format='yyyy-MM-dd HH:mm:ss' where transformation_type_id='35' and date_format='24';
update ds_transformation set date_format='yyyy-MM-dd HH:mm:ss.SSS' where transformation_type_id='35' and date_format='25';
update ds_transformation set date_format='yyyy-MM-ddTHH:mm:ss.SSS' where transformation_type_id='35' and date_format='26';
update ds_transformation set date_format='yyyy-MM-ddTHH:mm:ss.SSSZ' where transformation_type_id='35' and date_format='27';
update ds_transformation set date_format='dd MMM yyyy HH:mm:ss:SSS' where transformation_type_id='35' and date_format='28';
update ds_transformation set date_format='dd/MM/yyyy HH:mm:ss:SSS' where transformation_type_id='35' and date_format='29';

------ 新增版本控制,数据结构变化必须提高第二位版本 2015/7/23 by zhudebin ----------
insert into DS_SYS_SERVER_PARAMETER(name,value,data_type,is_collection) values('VERSION','1.7.0','N','N')
