UPDATE DS_SYS_SERVER_PARAMETER SET value='2.0.0' where name = 'VERSION';

DELETE FROM ds_tran_input_definition;
/* 增加了新的trans inputs */
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('VIRTUAL', 0, 21, '和squidColumn/referenceColumn绑定的虚拟转换。');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CONSTANT', -1, 0, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CHOICE', 9999, 21, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CONCATENATE', 9999, 9, '输入字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TERMEXTRACT', 0, 9, '要分析的源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TERMEXTRACT', 1, 9, '表达式');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TERMEXTRACT', 2, 2, '提取索引');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SPLIT', 0, 9, '被拆分的字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SPLIT', 1, 9, '分隔符');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ASCII', 0, 9, '要转换的字符');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('UNICODE', 0, 9, '要转换的字符');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SIMILARITY', 0, 9, '要对比的第一个字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SIMILARITY', 1, 9, '要对比的第二个字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CHAR', 0, 2, 'ASCII数值');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('PATTERNINDEX', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('PATTERNINDEX', 1, 9, '要搜索的目标字符串表达式');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('REPLICATE', 0, 9, '被重复的字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('REPLICATE', 1, 2, '重复的次数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('NUMERICTOSTRING', 0, 6, '要转化的数值');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('STRINGTONUMERIC', 0, 9, '要转化的字符串数值');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('REPLACE', 0, 9, '在此字符串中搜索');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('REPLACE', 1, 9, '替换成此字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('REPLACE', 2, 9, '匹配模式');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('LEFT', 0, 9, '被截取的源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('LEFT', 1, 2, '截取的长度');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RIGHT', 0, 9, '被截取的源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RIGHT', 1, 2, '截取的长度');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SUBSTRING', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SUBSTRING', 1, 2, '开始截取的位置');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SUBSTRING', 2, 2, '截取的长度');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('LENGTH', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('REVERSE', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('LOWER', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('UPPER', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('LEFTTRIM', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RIGHTTRIM', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TRIM', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SYSTEMDATETIME', -1, 0, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('STRINGTODATETIME', 0, 9, '要转换的日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('DATETIMETOSTRING', 0, 13, '要转换的日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('YEAR', 0, 13, '要转换的日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MONTH', 0, 13, '要转换的日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('DAY', 0, 13, '要转换的日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('DATEDIFF', 0, 13, '开始日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('DATEDIFF', 1, 13, '结束日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('FORMATDATE', 0, 9, '日期值');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ABS', 0, 6, '数值');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RANDOM', -1, 0, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ACOS', 0, 6, '-1到+1之间的浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('EXP', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ROUND', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ROUND', 1, 2, '舍入长度');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ASIN', 0, 6, '-1到+1之间的浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('FLOOR', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SIGN', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ATAN', 0, 6, '-∞到+∞');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('LOG', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SIN', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('LOG10', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SQRT', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CEILING', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('PI', -1, 0, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SQUARE', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('COS', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('POWER', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('POWER', 1, 2, '幂');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TAN', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('COT', 0, 6, '-∞到+∞，且不等于kπ，k∈Z');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RADIANS', 0, 6, '浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CALCULATION', 0, 6, '参加运算的第一个浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CALCULATION', 1, 6, '参加运算的第二个浮点数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MOD', 0, 2, '参加运算的整数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MOD', 1, 2, '模');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('PROJECTID', -1, 0, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('PROJECTNAME', -1, 0, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SQUIDFLOWID', -1, 0, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SQUIDFLOWNAME', -1, 0, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('JOBID', -1, 0, '');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TOKENIZATION', 0, 9, '分词文本');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('PREDICT ', 0, 10, '预测数据');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('PREDICT ', 1, 21, '预测数据的KEY');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('NUMASSEMBLE', 9999, 6, '浮点型输入');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TRAIN', 0, 10, '训练数据');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('NUMERICCAST', 0, 6, '被转换的数值输入');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('NUMERICCAST', 1, 2, '舍入的位数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('INVERSEQUANTIFY', 0, 6, '浮点输入');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CSNTOSTRING', 0, 10, 'CSN输入');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('COUNTRY', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('PROVINCE', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CITY', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('DISTRICT', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('STREET', 0, 9, '源字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('DATEPART', 0, 13, '原始日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('DATETOUNIXTIME', 0, 13, '要转换的日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('UNIXTIMETODATE', 0, 1, '要转换unix时间戳整数');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('DATEINC', 0, 13, '要做增减运算的日期');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MAPPUT', 0, 1022, '原始集合');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MAPPUT', 1, 9, '要添加的元素键');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MAPPUT', 2, 21, '要添加的元素值');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MAPGET', 0, 1022, '原始集合');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MAPGET', 1, 9, '要获取的元素键');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MAPREMOVE', 0, 1022, '原始集合');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('MAPREMOVE', 1, 9, '要移除的元素键');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ARRAYPUT', 0, 86, '原始集合');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ARRAYPUT', 1, 2, '要添加的元素键');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ARRAYPUT', 2, 21, '要添加的元素值');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ARRAYGET', 0, 86, '原始集合');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ARRAYGET', 1, 2, '要获取的元素键');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ARRAYREMOVE', 0, 86, '原始集合');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('ARRAYREMOVE', 1, 2, '要移除的元素键');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('DATEFORMAT', 0, 13, '将时间类型格式化为字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SPLIT2ARRAY', 0, 9, '将字符串分割为数组');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('SPLIT2ARRAY', 1, 9, '分隔符');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TERMEXTRACT2ARRAY', 0, 9, '需要提取的原始字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TERMEXTRACT2ARRAY', 1, 9, '表达式');

/* 删除表中冗余的字段 */
ALTER TABLE ds_transformation DROP COLUMN REG_EXPRESSION;
ALTER TABLE ds_transformation DROP COLUMN TERM_INDEX;
ALTER TABLE ds_transformation DROP COLUMN DELIMITER;
ALTER TABLE ds_transformation DROP COLUMN REPLICA_COUNT;
ALTER TABLE ds_transformation DROP COLUMN `LENGTH`;
ALTER TABLE ds_transformation DROP COLUMN START_POSITION;
ALTER TABLE ds_transformation DROP COLUMN POWER;
ALTER TABLE ds_transformation DROP COLUMN MODULUS;

/* 为trans input 增加value字段*/
ALTER TABLE ds_tran_inputs ADD INPUT_VALUE VARCHAR(50);


/* 增加新表 HDFS落地 */
CREATE TABLE ds_dest_hdfs_squid
(ID int NOT NULL AUTO_INCREMENT,
HOST varchar(50),
HDFS_PATH VARCHAR(200),
FILE_FORMATE int,
ZIP_TYPE int,
SAVE_TYPE int,
COLUMN_DELIMITER VARCHAR (256),
ROW_DELIMITER VARCHAR (256),
PRIMARY KEY (ID));

insert into ds_squid_type (ID, CODE, DESCRIPTION) values (46, 46, 'DEST_HDFS');

CREATE TABLE ds_dest_hdfs_column
(ID int NOT NULL AUTO_INCREMENT,
COLUMN_ID int NOT NULL,
SQUID_ID int NOT NULL,
IS_DEST_COLUMN int,
FIELD_NAME varchar(200),
COLUMN_ORDER int,
PRIMARY KEY (ID));

/* 增加impala落地 */
INSERT INTO ds_squid_type (ID, CODE, DESCRIPTION) VALUES (47, 47, 'DEST_IMPALA');
CREATE TABLE ds_dest_impala_squid
(
  ID INT NOT NULL AUTO_INCREMENT,
  HOST VARCHAR (50),
  STORE_NAME VARCHAR (50),
  IMPALA_TABLE_NAME VARCHAR (50),
  AUTHENTICATION_TYPE INT,
  PRIMARY KEY (ID)
);
CREATE TABLE ds_dest_impala_column
(ID int NOT NULL AUTO_INCREMENT,
COLUMN_ID int NOT NULL,
SQUID_ID int NOT NULL,
IS_DEST_COLUMN int,
FIELD_NAME varchar(200),
COLUMN_ORDER int,
PRIMARY KEY (ID));



/* 为ds_dm_squid增加用于关联分析的字段 */
INSERT INTO ds_squid_type (ID, CODE, DESCRIPTION) VALUES (48, 48, 'ASSOCIATION_RULES');
ALTER TABLE ds_dm_squid ADD MIN_SUPPORT DOUBLE(64,15);
ALTER TABLE ds_dm_squid ADD MIN_CONFIDENCE DOUBLE(64,15);

/* 增加CSV组装Trans */
INSERT INTO ds_transformation_type (ID, CODE, OUTPUT_DATA_TYPE, DESCRIPTION) VALUES (97, 'CSVASSEMBLE', 10, '把多个字符串拼接成CSV格式的字符串');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('CSVASSEMBLE', 9999, 9, '要组合CSV的字符串');

INSERT INTO ds_transformation_type (ID, CODE, OUTPUT_DATA_TYPE, DESCRIPTION) VALUES (98, 'RULESQUERY', 1022, '用于关联规则查询');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RULESQUERY', 0, 15, '前项');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RULESQUERY', 1, 2, '前项中的元素数量');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RULESQUERY', 2, 15, '后项');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RULESQUERY', 3, 2, '后项中的元素数量');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RULESQUERY', 4, 6, '最小可信度');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RULESQUERY', 5, 6, '最小规则支持度');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RULESQUERY', 6, 6, '最小提升度');
INSERT INTO ds_tran_input_definition (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('RULESQUERY', 7, 2, '规则数量');

/* 为了优化性能在Trans表内增加两个字段 */
ALTER TABLE ds_tran_inputs ADD INPUT_DATA_TYPE INT;
ALTER TABLE ds_tran_inputs ADD DESCRIPTION VARCHAR(500);

/*往ds_hdfs_connection表中插入including_subfolders_flag字段 表示是否选择递归的状态 */
ALTER TABLE DS_HDFS_CONNECTION ADD INCLUDING_SUBFOLDERS_FLAG BIGINT;
/* 修改including_subfolders_flag字段类型bigInt改为int*/
ALTER TABLE DS_HDFS_CONNECTION MODIFY INCLUDING_SUBFOLDERS_FLAG INT;
/*修改ds_squid中的filter属性的长度*/
ALTER TABLE DS_SQUID MODIFY COLUMN `FILTER` NVARCHAR(2000);