--- 升级到1.10 ------
UPDATE DS_SYS_SERVER_PARAMETER SET value='1.11.0' where name = 'VERSION';
--- 新增kafka抽取 ---
CREATE TABLE DS_KAFKA_CONNECTION
(
	id INT NOT NULL,
	zkquorum VARCHAR(200) 	 NULL,
	PRIMARY KEY (id)
);
CREATE TABLE DS_KAFKA_EXTRACT
(
	id INT 	NOT NULL,
	is_persisted CHAR(1) 	 NULL,
	table_name VARCHAR(100) 	 NULL,
	destination_squid_id INT 	 NULL,
	numPartitions INT 	 NULL,
	group_id VARCHAR(100),
	source_table_id      int,
	PRIMARY KEY(id)
);
--- 添加squid类型 ---
INSERT INTO  DS_SQUID_TYPE (ID,CODE,DESCRIPTION)VALUES(41,41,'KAFKA');
INSERT INTO  DS_SQUID_TYPE (ID,CODE,DESCRIPTION)VALUES(42,42,'KAFKAEXTRACT');

-- squidflow 添加 squidflow_type 字段  0或者空为批处理,1为流式 ---
alter table DS_SQUID_FLOW add COLUMN squidflow_type int DEFAULT 0;
alter table DS_DOC_EXTRACT add COLUMN compressicon_codec int DEFAULT 0;
alter table DS_SOURCE_TABLE add COLUMN is_directory BOOLEAN DEFAULT false;

-- HBASE抽取 --
CREATE TABLE DS_HBASE_CONNECTION
(
	id INT NOT NULL,
	url VARCHAR(200) 	 NULL,
	PRIMARY KEY (id)
);
CREATE TABLE DS_HBASE_EXTRACT
(
	id                   int not null,
  is_persisted     	char(1),
  table_name           varchar(100) ,
  destination_squid_id int,
  is_indexed        	char(1),
  top_n                int,
  truncate_existing_data_flag int,
  process_mode         int,
  cdc                  int,
  exception_handling_flag int,
  source_table_id      int,
  filter_type          int,
  scan                 LONGVARCHAR,
  code                 LONGVARCHAR,
  primary key (id)
);
--- 添加squid类型 ---
INSERT INTO  DS_SQUID_TYPE (ID,CODE,DESCRIPTION)VALUES(43,43,'HBASE');
INSERT INTO  DS_SQUID_TYPE (ID,CODE,DESCRIPTION)VALUES(44,44,'HBASEEXTRACT');
----修改DS_SOURCE_TABLE的长度-----
ALTER TABLE DS_SOURCE_TABLE ALTER COLUMN (TABLE_NAME VARCHAR(2500) NOT NULL);

---  yarn 作业状态表
create table DS_SYS_APPLICATION_STATUS(
  id int not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
  repository_id int,
  project_id int,
  squidflow_id int,
  launch_user_id int,
  stop_user_id int,
  application_id varchar(100),
  status varchar(20),
  config varchar(500),
  create_date datetime default CURRENT_timestamp not null,
  update_date datetime ,
  stop_date datetime ,
  primary key(id)
)