--- 升级到2.0.0 ------
UPDATE DS_SYS_SERVER_PARAMETER SET value='2.0.0' where name = 'VERSION';
INSERT INTO  DS_SQUID_TYPE (ID,CODE,DESCRIPTION)VALUES(45,45,'STREAM_STAGE');
ALTER TABLE DS_DOC_EXTRACT alter TABLE_NAME VARCHAR(500);
ALTER TABLE DS_SQUID alter TABLE_NAME VARCHAR(500);
ALTER TABLE DS_SQUID alter NAME VARCHAR(1000);
INSERT INTO DS_TRANSFORMATION_TYPE (CODE, OUTPUT_DATA_TYPE, DESCRIPTION) VALUES ('TERMEXTRACT2ARRAY', 86, '提取符合表达式要求的字符串结果集');
INSERT INTO DS_TRAN_INPUT_DEFINITION (CODE, INPUT_ORDER, INPUT_DATA_TYPE, DESCRIPTION) VALUES ('TERMEXTRACT2ARRAY', 0, 9, '需要提取的原始字符串');
INSERT INTO DS_TRANSFORMATION_TYPE (CODE, OUTPUT_DATA_TYPE, DESCRIPTION) VALUES ('TASKID', 9, '返回TASK ID');
update DS_TRANSFORMATION_TYPE set ID = 87 where CODE = 'TASKID'; /* 插入数据后需要对这个Trans的ID进行更新，因为代码中的枚举已经写成了87 */
ALTER TABLE DS_DATA_SQUID ADD WINDOW_DURATION BIGINT;including_subfolders_flag
ALTER TABLE DS_DATA_SQUID ADD ENABLE_WINDOW CHARACTER;

