--- 升级到1.8 ------
UPDATE DS_SYS_SERVER_PARAMETER SET value='1.8.0' where name = 'VERSION';
insert into DS_SYS_SERVER_PARAMETER(name,value,data_type,is_collection) values('SPLIT_COLUMN_FILTER','{"MYSQL":"LONGBLOB,MEDIUMBLOB,TINYBLOB","ORACLE":"BLOB,BINARY_DOUBLE,NCLOB,CLOB","SQLSERVER":"BINARY,VARBINARY,TIMESTAMP,UNIQUEIDENTIFIER,IMAGE,XML,HIERARCHYID,TEXT,NTEXT,DATETIMEOFFSET,SQL_VARIANT"}','N','N');

alter TABLE DS_DATA_SQUID add column split_col varchar(128);
alter TABLE DS_DATA_SQUID add split_num  INT DEFAULT 0;
