--- 升级到1.10 ------
UPDATE DS_SYS_SERVER_PARAMETER SET value='1.10.0' where name = 'VERSION';
--- 分片列控制 ---
update DS_SYS_SERVER_PARAMETER set value = '{"MYSQL":"LONGBLOB,MEDIUMBLOB,TINYBLOB,XML","ORACLE":"BLOB,BINARY_DOUBLE,NCLOB,CLOB","SQLSERVER":"BINARY,VARBINARY,TIMESTAMP,UNIQUEIDENTIFIER,IMAGE,XML,HIERARCHYID,TEXT,NTEXT,DATETIMEOFFSET,SQL_VARIANT,BIT"}' where name = 'SPLIT_COLUMN_FILTER';