--- 升级到1.9 ------
UPDATE DS_SYS_SERVER_PARAMETER SET value='1.9.0' where name = 'VERSION';
create table if not exists DS_DEST_ES_SQUID
(
   id                   int not null,
   ip                   varchar(20),
   port                 int,
   esindex              varchar(200),
   estype               varchar(200),
   primary key (id)
);

create table if not EXISTS DS_ES_COLUMN
(
   id                   int not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
   column_id            int not null,
   squid_id             int not null,
   is_mapping_id        int,
   field_name           varchar(200),
   is_persist           int
);

INSERT INTO  DS_SQUID_TYPE (ID,CODE,DESCRIPTION)VALUES(40,40,'DESTES');

--- 2015-12-22 --  添加一个transformation split2array ---
INSERT INTO  DS_TRANSFORMATION_TYPE  (ID,CODE,OUTPUT_DATA_TYPE,DESCRIPTION)VALUES(95,'SPLIT2ARRAY',86,'将字符串分割为数组');
INSERT INTO DS_TRAN_INPUT_DEFINITION(CODE,INPUT_ORDER,INPUT_DATA_TYPE,DESCRIPTION)VALUES('SPLIT2ARRAY', 0, 9,'将字符串分割为数组');